---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vericase-config
  namespace: vericase
data:
  # AWS Mode
  USE_AWS_SERVICES: "true"
  AWS_REGION: eu-west-2
  
  # S3 Configuration (empty endpoint to use IRSA)
  MINIO_ENDPOINT: ""
  MINIO_PUBLIC_ENDPOINT: ""
  MINIO_ACCESS_KEY: ""
  MINIO_SECRET_KEY: ""
  MINIO_BUCKET: vericase-docs-prod-526015377510
  
  # Redis (ElastiCache)
  REDIS_URL: redis://clustercfg.vericase-redis.dbbgbx.euw2.cache.amazonaws.com:6379
  CELERY_QUEUE: ocr
  
  # OpenSearch with TLS
  OPENSEARCH_HOST: vpc-vericase-opensearch-sl2a3zd5dnrbt64bssyocnrofu.eu-west-2.es.amazonaws.com
  OPENSEARCH_PORT: "443"
  OPENSEARCH_USE_SSL: "true"
  OPENSEARCH_VERIFY_CERTS: "true"
  OPENSEARCH_INDEX: documents
  
  # Tika service
  TIKA_URL: http://tika:9998
  
  # API Settings
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  CORS_ORIGINS: "*"
  
  # JWT Settings
  JWT_SECRET: change-this-to-a-secure-random-string
  JWT_ISSUER: vericase-docs
  JWT_EXPIRE_MIN: "7200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vericase-api
  namespace: vericase
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vericase-api
  template:
    metadata:
      labels:
        app: vericase-api
    spec:
      serviceAccountName: vericase-api-sa
      containers:
        - name: api
          image: 526015377510.dkr.ecr.eu-west-2.amazonaws.com/vericase-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: vericase-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vericase-db
                  key: DATABASE_URL
            - name: PORT
              value: "8000"
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: vericase-api
  namespace: vericase
spec:
  type: LoadBalancer
  selector:
    app: vericase-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vericase-worker
  namespace: vericase
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vericase-worker
  template:
    metadata:
      labels:
        app: vericase-worker
    spec:
      serviceAccountName: vericase-worker-sa
      containers:
        - name: worker
          image: 526015377510.dkr.ecr.eu-west-2.amazonaws.com/vericase-worker:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: vericase-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vericase-db
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "4Gi"
